# Generated by Django 2.2.8 on 2019-12-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0003_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='added_at',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True),
        ),
    ]
