# Generated by Django 2.2.5 on 2020-03-10 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0004_message_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.TimeField(default=datetime.datetime(2020, 3, 10, 17, 20, 36, 583518), verbose_name='Время создания'),
        ),
    ]
