# Generated by Django 2.2.5 on 2020-03-10 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0005_auto_20200310_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.TimeField(default=datetime.datetime(2020, 3, 10, 17, 23, 1, 532013, tzinfo=utc), verbose_name='Время создания'),
        ),
    ]
